<a href="https://colab.research.google.com/github/NitheshKasiRaju/PytorchTutorials/blob/main/Pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor
A tensor is a generalization of scalars, vectors, and matrices to higher dimensions. It is a multidimensional array used to represent data.

#Why Tensors Matter:
Tensors are the input and output of every operation in a neural network. All computations—like matrix multiplication, addition, activation functions—are performed using tensor operations, often accelerated by GPUs.

In [1]:
import torch

In [2]:
import numpy as np

#Lists

In [4]:
my_list = [[1,2,3,4,5,6],[7,8,9,10,11,12]]
my_list

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]]

#Numpy Array

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.69730246, 0.01925385, 0.5731237 , 0.56019786],
       [0.42653969, 0.94728242, 0.8199736 , 0.49413541],
       [0.59238129, 0.30630519, 0.6777439 , 0.91962269]])

In [7]:
np1.dtype

dtype('float64')

#Tensor

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
#create a tensor out of numpy
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6973, 0.0193, 0.5731, 0.5602],
        [0.4265, 0.9473, 0.8200, 0.4941],
        [0.5924, 0.3063, 0.6777, 0.9196]], dtype=torch.float64)