<a href="https://colab.research.google.com/github/NitheshKasiRaju/PytorchTutorials/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# add longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
#division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [16]:
# Exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [17]:
# Reassignment

In [18]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a = tensor_a + tensor_b

In [20]:
tensor_a

tensor([ 6,  8, 10, 12])

In [21]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [22]:
tensor_a

tensor([11, 14, 17, 20])